#!/bin/bash
bold=$(tput bold)
normal=$(tput sgr0)

echo "${bold}[PRECHECKING]${normal}"
echo "${bold}[Updating apt-cache]${normal}"
sudo apt-get update

echo ""
echo "${bold}[UPDATING]${normal}"
echo "${bold}[Updating SYSTEM]${normal}"
sudo apt-get dist-upgrade
read -p "Press any key to continue..." -n1 -s
echo ""
echo "${bold}[Updating SHELL EXTENSIONS]${normal}"
echo "${bold}[Updating powerlevel10k]${normal}"
git -C ~/.oh-my-zsh/custom/themes/powerlevel10k pull
echo "${bold}[Updating zsh-autosuggestions]${normal}"
git -C ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions pull
echo "${bold}[Updating SCRIPTS]${normal}"
echo "${bold}[Updating fnd]${normal}"
curl https://raw.githubusercontent.com/voltamage/notes/master/armbian/scripts/fnd > ~/scripts/fnd -#
sudo chmod u+x ~/scripts/fnd
echo "${bold}[Updating maintain]${normal}"
curl https://raw.githubusercontent.com/voltamage/notes/master/armbian/scripts/maintain > ~/scripts/maintain -#
sudo chmod u+x ~/scripts/maintain
echo "${bold}[Updating mfnd]${normal}"
curl https://raw.githubusercontent.com/voltamage/notes/master/armbian/scripts/mfnd > ~/scripts/mfnd -#
sudo chmod u+x ~/scripts/mfnd
echo "${bold}[Updating ALIASES]${normal}"
curl https://raw.githubusercontent.com/voltamage/notes/master/armbian/.oh-my-zsh/custom/aliases.zsh > ~/.oh-my-zsh/custom/aliases.zsh -#

echo ""
echo "${bold}[CLEANING]${normal}"
echo "${bold}[Cleaning orphaned packages]${normal}"
sudo apt-get autoremove --purge
echo "${bold}[Cleaning package caches]${normal}"
sudo apt-get clean
echo "${bold}[Cleaning junk directories]${normal}"
sudo rm -rf /root/.lesshst
sudo rm -rf /root/.wget-hsts
rm -rf ~/.lesshst
rm -rf ~/.wget-hsts
/home/$USER/scripts/rmshit.py

echo ""
echo "${bold}[POSTCHECKING]${normal}"
echo "${bold}[Checking reboot]${normal}"
sudo needrestart
echo "${bold}[DONE]${normal}"
exec zsh
