#!/bin/bash
bold=$(tput bold)
normal=$(tput sgr0)

echo "${bold}[PRECHECKING]${normal}"
echo "${bold}[Updating apt-cache]${normal}"
sudo apt-get update

echo "${bold}[UPDATING]${normal}"
echo "${bold}[Updating SYSTEM]${normal}"
sudo apt-get dist-upgrade
read -p "Press any key to continue..." -n1 -s
echo ""
echo "${bold}[Updating PACKAGES]${normal}"
echo "${bold}[Updating youtube-dl]${normal}"
sudo youtube-dl -U
echo "${bold}[Updating SHELL EXTENSIONS]${normal}"
echo "${bold}[Updating powerlevel10k]${normal}"
git -C ~/.oh-my-zsh/custom/themes/powerlevel10k pull
echo "${bold}[Updating zsh-autosuggestions]${normal}"
git -C ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions pull
echo "${bold}[Updating SCRIPTS]${normal}"
echo "${bold}[Updating msrsync]${normal}"
curl -# https://raw.githubusercontent.com/jbd/msrsync/master/msrsync > ~/scripts/msrsync
echo "${bold}[Updating rmshit.py]${normal}"
curl -# https://raw.githubusercontent.com/lahwaacz/Scripts/master/rmshit.py > ~/scripts/rmshit.py
sed -i '/.viminfo/d' ~/scripts/rmshit.py

echo "${bold}[CLEANING]${normal}"
echo "${bold}[Cleaning orphaned packages]${normal}"
sudo apt-get autoremove --purge
echo "${bold}[Cleaning package caches]${normal}"
sudo apt-get clean
echo "${bold}[Cleaning junk directories]${normal}"
sudo rm -rf /root/.lesshst
sudo rm -rf /root/.wget-hsts
rm -rf ~/.lesshst
rm -rf ~/.wget-hsts
rmshit.py

echo "${bold}[POSTCHECKING]${normal}"
echo "${bold}[Checking reboot]${normal}"
sudo needrestart
echo "${bold}[DONE]${normal}"
