#!/bin/bash

# STEAM
# This script is special, as it allows Steam installation on as many prefixes as possible
# We want to require as few packages as possible, so the user can reinstall them at will
# For example, it's easy to install vcrun2005, however it is much harder to uninstall
# So gecko is the only essential package, and the rest are avoided
#
# SKYRIM
# Wine 1.7.36 -> 2.22 (emergency update, because of many install issues reported from users)
# POL_RequiredVersion "4.2.12"
# Note (for a future update): replacing dotnet35 by dotnet40 will does the 'ptrace' issue.
# (I grabbed both versions and kept the 'ptrace' check)
 
[ "$PLAYONLINUX" = "" ] && exit 0
source "$PLAYONLINUX/lib/sources"
 
TITLE="The Elder Scrolls V: Skyrim"
PREFIX="Skyrim"
WINEVERSION="5.2"
AUTHOR="voltamage"
EDITOR="Bethesda Softworks"
GAME_URL="https://elderscrolls.bethesda.net/skyrim/"
STEAM_ID="72850"

# Starting the script
POL_GetSetupImages "http://files.playonlinux.com/resources/setups/Skyrim/top.jpg" "http://files.playonlinux.com/resources/setups/Skyrim/left.jpg" "$TITLE"
POL_SetupWindow_Init
POL_SetupWindow_SetID 1005
 
# Starting debugging API
POL_Debug_Init
 
POL_SetupWindow_presentation "$TITLE" "$EDITOR" "$GAME_URL" "$AUTHOR" "$PREFIX"
# Check Kernel ptrace
if [ -e "/proc/sys/kernel/yama/ptrace_scope" ]; then
        PTRACE_CHECK=`cat /proc/sys/kernel/yama/ptrace_scope`
        if [ "$PTRACE_CHECK" != 0 ]; then
                POL_Debug_message "$(eval_gettext 'The game will fail to launch until you set /proc/sys/kernel/yama/ptrace_scope to 0')" "$TITLE"
        fi
fi
 
# Setting prefix path
POL_Wine_SelectPrefix "$PREFIX"
 
# Downloading wine if necessary and creating prefix
POL_System_SetArch "x86"
POL_Wine_PrefixCreate "$WINEVERSION"
 
# Installing mandatory dependencies
POL_Wine_InstallFonts
POL_Call POL_Install_corefonts
POL_Call POL_Install_vcrun2008 # Fix game issue, doesn't run on 64 bit installs
POL_Call POL_Install_dotnet35 # Fix launcher issue, also doesn't seem to run on 64 bit installs
POL_Call POL_Install_dotnet40 # ENB
POL_Call POL_Install_dxfullsetup # Fix game crash
POL_Call POL_Install_d3dcompiler_43 # ENB
POL_Call POL_Install_d3dx9_43 # ENB
POL_Call POL_Install_d3dx9_36 # ENB
# POL_Call POL_Install_gecko # Probably not necessary, gecko is an IE replacement, still doesn't fix steam rendering
POL_Call POL_Install_xact # Audio fix
# Missing dotnet, according to Mod Organizer
# Missing how to add d3d9.dll to winecfg
POL_Function_FontsSmoothRGB
POL_Wine_OverrideDLL "" "dwrite" # Necessary for initial install, but disable later

# Fix PulseAudio issue
which pulseaudio && Set_OS "win7"
 
# Set graphic card information keys for wine
POL_Wine_SetVideoDriver
 
# Fix for Skyrim mouse
POL_Wine_X11Drv "GrabFullscreen" "Y"
  
# Installing Steam
cd "$POL_USER_ROOT/wineprefix/$PREFIX/drive_c/"
POL_Download "http://media.steampowered.com/client/installer/SteamSetup.exe"
 
POL_SetupWindow_wait "$(eval_gettext 'Please complete the setup wizard and run Steam')" "$(eval_gettext '$TITLE - Steam Installation')"
POL_Wine "SteamSetup.exe"
POL_SetupWindow_message "$(eval_gettext 'Log into your Steam account, and exit Steam completely after you are done.\n\nClick Next to continue.')" "$TITLE - Steam Login"
 
# Fix to disable Steam overlay
# May not be necessary anymore, but missing text is annoying, so I'm disabling it
POL_Wine_OverrideDLL "" "gameoverlayrenderer"
 
# Making shortcut
POL_Shortcut "Steam.exe" "Steam"

# Mandatory pre-install fix for steam
POL_Call POL_Install_steam_flags "$STEAM_ID"
 
# Shortcut done before install for Steam version
POL_Shortcut "Steam.exe" "$TITLE" "$TITLE.png" "steam://rungameid/$STEAM_ID" "Game;RolePlaying;"
 
# Begin game installation
POL_SetupWindow_Close
cd "$WINEPREFIX/drive_c/$PROGRAMFILES/Steam"
POL_Wine start /unix "Steam.exe" steam://install/$STEAM_ID

exit 0
