#!/bin/bash
bold=$(tput bold)
normal=$(tput sgr0)

echo "${bold}[PATCH CHECK]${normal}"
#echo "No patch available"
echo "Testing sources update"
read -p "Press any key to continue..." -n1 -s
echo ""

echo "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /tmp/docker.list
#sudo mv /etc/apt/sources.list.d/docker.list

DEBID=$(grep 'VERSION_ID=' /etc/os-release | cut -d '=' -f 2 | tr -d '"')
DEBVER=$(grep 'VERSION=' /etc/os-release | grep -Eo '[a-z]+')
echo "deb https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/${DEBID}/$(dpkg --print-architecture)/apt ${DEBVER} main" > /tmp/gluster.list
#sudo mv /tmp/gluster.list /etc/apt/sources.list.d/gluster.list

echo ""
echo "${bold}[DONE]${normal}"
