#!/bin/bash
bold=$(tput bold)
normal=$(tput sgr0)

echo "${bold}[PATCH CHECK]${normal}"
echo "No patch available"
bash -c "$(git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k)"
read -p "Press any key to continue..." -n1 -s
echo ""
