#!/bin/bash
bold=$(tput bold)
normal=$(tput sgr0)

echo "${bold}[PATCH CHECK]${normal}"
echo "No patch available"
echo ""

echo "${bold}[FETCHING LATEST UPDATER]${normal}"
cp ~/scripts/updater /tmp/updater
curl https://raw.githubusercontent.com/voltamage/notes/master/armbian/scripts/updater > ~/scripts/updater -#
echo ""
