#!/bin/bash
bold=$(tput bold)
normal=$(tput sgr0)

echo "${bold}[PATCH CHECK]${normal}"
echo "No patch available"
comm -12 <(grep 'sudo apt-get install' ~/.zsh_history | sed '/|/d' | awk '{$1=$2=$3=$4=""; print $0}' | sed s/\\s/\\n/g | sort -n) <(dpkg --list | awk '{print $2}' | sed 's/:armhf//' | sort -n) | sed '/^$/d' > ~/.pkglist
echo ""

echo "${bold}[FETCHING LATEST UPDATER]${normal}"
cp ~/scripts/updater /tmp/updater
curl https://raw.githubusercontent.com/voltamage/notes/master/armbian/scripts/updater > ~/scripts/updater -#
sudo chmod u+x ~/scripts/updater
echo ""
