#!/bin/bash
bold=$(tput bold)
normal=$(tput sgr0)

sudo apt-get install lvm2
dd if=/dev/zero of=/dev/sda bs=512 count=1
sudo pvcreate /dev/sda
sudo vgcreate vg_glusterfs /dev/sda

mkfs.xfs -f -i size=512 -n size=8192 DEVICE

sudo mkdir /mnt/oceanus
sudo cp /etc/fstab /etc/fstab.bak
cp /etc/fstab /tmp/fstab

echo "/dev/vg_glusterfs/LV /mnt/oceanus xfs rw,inode64,noatime,nouuid 1 2" >> /tmp/fstab
sudo mv /tmp/fstab /etc/fstab
sudo mount -av
