#!/bin/bash
bold=$(tput bold)
normal=$(tput sgr0)

sudo apt-get -y install acl glusterfs-server rpcbind xfsprogs

echo "${bold}[Configuring GLUSTERD SERVICE]${normal}"
sudo systemctl enable --now glusterd.service

echo "${bold}[GLUSTERFS]${normal}"
echo "${bold}[Formatting filesystem]${normal}"
dd if=/dev/zero of=/dev/sda bs=512 count=1
sudo pvcreate /dev/sda
sudo vgcreate gluster /dev/sda
sudo lvcreate --thin gluster/brick --extents 100%FREE --poolmetadatasize 16GB --zero n
sudo mkfs.xfs -f -i size=512 -n size=8192 /dev/gluster/brick
echo "${bold}[Mounting filesystem]${normal}"
sudo mkdir /mnt/gluster
sudo cp /etc/fstab /etc/fstab.bak
cp /etc/fstab /tmp/fstab
echo "/dev/gluster/brick /mnt/gluster xfs rw,inode64,noatime,nouuid 0 2" >> /tmp/fstab
sudo mv /tmp/fstab /etc/fstab
sudo mount -av

echo "${bold}[Review critical services]${normal}"
systemctl --type=service | grep 'rpcbind\|glusterd'
read -p "Press any key to continue..." -n1 -s
echo ""
echo "${bold}[Review fstab]${normal}"
cat /etc/fstab

echo ""
echo "${bold}[Review filesystem]${normal}"
read -p "Press any key to continue..." -n1 -s
echo ""
cat <(echo "[user folder]") <(ls -la ~/) <(echo "") <(echo "[scripts folder]") <(ls -la ~/scripts) <(echo "") <(echo "[root folder]") <(sudo ls -la /root) <(echo "") <(echo "[tmp folder]") <(ls -la /tmp) <(echo "") | less
echo "${bold}[Review mounts]${normal}"
read -p "Press any key to continue..." -n1 -s
echo ""
cat <(echo "[Mounts]") <(lsblk) <(echo "") <(echo "[Usage]") <(df -h) | less
echo "${bold}[Review LVM]${normal}"
read -p "Press any key to continue..." -n1 -s
echo ""
cat <(echo "[Physical volumes]") <(sudo pvdisplay) <(echo "[Volume groups]") <(sudo vgdisplay) <(echo "[Logical volumes]") <(sudo lvdisplay) <(echo "[Metadata]") <(sudo lvs -o+metadata_percent) | less

