#!/bin/bash
bold=$(tput bold)
normal=$(tput sgr0)

echo "${bold}[PRECHECKING]${normal}"
echo "${bold}[Updating apt-cache]${normal}"
sudo apt-get update

echo "${bold}[UPDATING]${normal}"
echo "${bold}[Updating SYSTEM]${normal}"
sudo apt-get dist-upgrade
read -p "Press any key to continue..." -n1 -s
echo ""

echo "${bold}[INSTALLING]${normal}"
echo "${bold}[Installing htop]${normal}"
sudo apt-get install htop
sed -i -e '/tree_view/c\tree_view=1' ~/.config/htop/htoprc
echo "${bold}[Installing ranger]${normal}"
sudo apt-get install file mediainfo ranger
echo "${bold}[Installing vim]${normal}"
sudo apt-get install vim
echo "SELECTED_EDITOR="/usr/bin/vim.basic"" > ~/.selected_editor
echo "${bold}[DONE]${normal}"
