#!/bin/bash
bold=$(tput bold)
normal=$(tput sgr0)

sudo apt-get install htop
sed -i -e '/tree_view/c\tree_view=1' ~/.config/htop/htoprc
sudo apt-get install file mediainfo ranger
sudo apt-get install vim
echo "SELECTED_EDITOR="/usr/bin/vim.basic"" > ~/.selected_editor
