#!/bin/bash
bold=$(tput bold)
normal=$(tput sgr0)

echo "${bold}[Configuring neofetch]${normal}"
mkdir ~/.config/neofetch
curl https://raw.githubusercontent.com/voltamage/notes/master/armbian/.config/neofetch/config.conf > ~/.config/neofetch/config.conf -#
neofetch
read -p "Press any key to continue..." -n1 -s
echo ""
