#!/bin/bash
bold=$(tput bold)
normal=$(tput sgr0)

echo "${bold}[PRECHECKING]${normal}"
echo "${bold}[Updating apt-cache]${normal}"
sudo apt-get update

echo "${bold}[UPDATING]${normal}"
echo "${bold}[Updating SYSTEM]${normal}"
sudo apt-get -y dist-upgrade

echo "${bold}[INSTALLING]${normal}"
echo "${bold}[Installing git]${normal}"
sudo apt-get -y install git
echo "${bold}[Installing vim]${normal}"
sudo apt-get -y install vim
echo "SELECTED_EDITOR="/usr/bin/vim.basic"" > ~/.selected_editor
sudo cp ~/.selected_editor /root
echo "${bold}[Installing zsh]${normal}"
sudo apt-get -y install zsh
echo "${bold}[Installing oh-my-zsh]${normal}"
yes | sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
sudo chsh --shell /usr/bin/zsh $USER

echo "${bold}[POSTCHECKING]${normal}"
echo "${bold}[Checking shell]${normal}"
awk -F: -v user="$USER" '$1 == user {print $NF}' /etc/passwd
read -p "Press any key to continue..." -n1 -s
echo ""
echo "${bold}[DONE]${normal}"
zsh
