#!/bin/bash
bold=$(tput bold)
normal=$(tput sgr0)

echo "${bold}[INSTALLING]${normal}"
echo "${bold}[Installing zsh-autosuggestions]${normal}"
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

echo "${bold}[CONFIGURING]${normal}"
mkdir ~/scripts
sed -i '/PATH=$HOME/ a export PATH=$HOME/scripts:$PATH' ~/.zshrc
sed -i '/ZSH_THEME="/c\ZSH_THEME="powerlevel10k/powerlevel10k"' ~/.zshrc
sed -i '/DISABLE_UPDATE_PROMPT/c\DISABLE_UPDATE_PROMPT="true"' ~/.zshrc
sed -i '/UPDATE_ZSH_DAYS/c\export UPDATE_ZSH_DAYS=1' ~/.zshrc
sed -i '/plugins=/c\plugins=(git zsh-autosuggestions)' ~/.zshrc
echo "alias aliases='vim /home/volt/.oh-my-zsh/custom/aliases.zsh && exec zsh'" > ~/.oh-my-zsh/custom/aliases.zsh
echo "${bold}[Script folder check]${normal}"
ls ~/ | grep scripts
echo "${bold}[Alias file check]${normal}"
cat ~/.oh-my-zsh/custom/aliases.zsh
echo "${bold}[DONE]${normal}"
