#!/bin/bash
bold=$(tput bold)
normal=$(tput sgr0)

echo "${bold}[INSTALLING]${normal}"
echo "${bold}[Installing acl]${normal}"
sudo apt-get -y acl
echo "${bold}[Installing aria2]${normal}"
sudo apt-get -y install aria2
mkdir ~/.config/aria2
curl https://raw.githubusercontent.com/voltamage/notes/master/armbian/.config/aria2/aria2.conf > ~/.config/aria2/aria2.conf -#
echo "${bold}[Installing armbian-config]${normal}"
sudo apt-get -y install armbian-config
echo "${bold}[Installing docker]${normal}"
sudo apt-get -y install apt-transport-https ca-certificates gnupg2 software-properties-common
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
sudo cp /etc/apt/sources.list /etc/apt/sources.list.bak
sudo add-apt-repository "deb [arch=armhf] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
sudo sed -i -e '/deb-src/d' -e '/^$/d' /etc/apt/sources.list
sudo apt-get update
sudo apt-get -y install docker-ce docker-ce-cli docker-compose
echo "${bold}[Installing glusterfs-server]${normal}"
sudo apt-get -y install glusterfs-server rpcbind
sudo systemctl enable --now glusterd
echo "${bold}[Installing hdparm (HDD park fix)]${normal}"
sudo apt-get -y install hdparm
curl https://dn.odroid.com/5422/script/odroid.shutdown > /tmp/odroid.shutdown -#
sudo install -o root -g root -m 0755 /tmp/odroid.shutdown /lib/systemd/system-shutdown/odroid.shutdown
rm /tmp/odroid.shutdown
echo "${bold}[Installing htop]${normal}"
sudo apt-get -y install htop
sudo rm -rf /root/.config/htop
sed -i -e '/tree_view/c\tree_view=1' ~/.config/htop/htoprc
echo "${bold}[Installing iotop]${normal}"
sudo apt-get -y install iotop
echo "${bold}[Installing lvm2]${normal}"
sudo apt-get -y install lvm2
echo "${bold}[Installing ncdu]${normal}"
sudo apt-get -y install ncdu
echo "${bold}[Installing neofetch]${normal}"
sudo apt-get -y install neofetch
mkdir ~/.config/neofetch
curl https://raw.githubusercontent.com/voltamage/notes/master/armbian/.config/neofetch/config.conf > ~/.config/neofetch/config.conf -#
echo "${bold}[Installing nload]${normal}"
sudo apt-get -y install nload
echo "${bold}[Installing nmap]${normal}"
sudo apt-get -y install nmap
echo "${bold}[Installing ranger]${normal}"
sudo apt-get -y install file mediainfo ranger
echo "${bold}[Installing rsync (for mysrsync]${normal}"
sudo apt-get -y install python rsync
echo "${bold}[Installing smartmontools (smartctl)]${normal}"
sudo apt-get -y install smartmontools
echo "${bold}[Installing sshfs]${normal}"
sudo apt-get -y install sshfs
echo "${bold}[Installing tmux]${normal}"
sudo apt-get -y install tmux
echo "${bold}[Installing xfsprogs]${normal}"
sudo apt-get -y install xfsprogs

echo "${bold}[POSTCHECKING]${normal}"
echo "${bold}[Checking updates]${normal}"
sudo apt-get update
sudo apt-get -y dist-upgrade
echo "${bold}[Sorting aliases]${normal}"
sort -n ~/.oh-my-zsh/custom/aliases.zsh > /tmp/aliases.zsh
mv /tmp/aliases.zsh ~/.oh-my-zsh/custom/aliases.zsh
echo "${bold}[Installing man-db]${normal}"
sudo apt-get -y install man-db
echo "${bold}[Installing needrestart / reboot check]${normal}"
sudo apt-get -y install needrestart
sudo needrestart
read -p "Press any key to continue..." -n1 -s
echo ""

dd if=/dev/zero of=/dev/sda bs=512 count=1
sudo pvcreate /dev/sda
sudo vgcreate vg_glusterfs /dev/sda
sudo lvcreate --thin vg_glusterfs/oceanus_brick --extents 100%FREE --poolmetadatasize 16GB --zero n
sudo mkfs.xfs -f -i size=512 -n size=8192 /dev/vg_glusterfs/oceanus_brick

sudo mkdir /mnt/oceanus
sudo cp /etc/fstab /etc/fstab.bak
cp /etc/fstab /tmp/fstab
echo "/dev/vg_glusterfs/oceanus_brick /mnt/oceanus xfs rw,inode64,noatime,nouuid 0 2" >> /tmp/fstab
sudo mv /tmp/fstab /etc/fstab
sudo mount -av


sudo timedatectl set-timezone America/Los_Angeles
timedatectl set-ntp true
timedatectl
locale | grep LANG=
curl https://raw.githubusercontent.com/voltamage/notes/master/armbian/.oh-my-zsh/custom/aliases.zsh > ~/.oh-my-zsh/custom/aliases.zsh -#


curl https://raw.githubusercontent.com/voltamage/notes/master/armbian/scripts/maintain > ~/scripts/maintain -#
sudo chmod u+x ~/scripts/maintain
curl https://raw.githubusercontent.com/voltamage/notes/master/armbian/scripts/update > ~/scripts/update -#
sudo chmod u+x ~/scripts/update
curl https://raw.githubusercontent.com/voltamage/notes/master/armbian/scripts/fnd > ~/scripts/fnd -#
sudo chmod u+x ~/scripts/fnd
curl https://raw.githubusercontent.com/voltamage/notes/master/armbian/scripts/mfnd > ~/scripts/mfnd -#
sudo chmod u+x ~/scripts/mfnd
curl https://raw.githubusercontent.com/jbd/msrsync/master/msrsync > ~/scripts/msrsync -#
sudo chmod u+x ~/scripts/msrsync
curl https://raw.githubusercontent.com/lahwaacz/Scripts/master/rmshit.py > ~/scripts/rmshit.py -#
sudo chmod u+x ~/scripts/rmshit.py

echo "${bold}[DONE]${normal}"
exec zsh
