#!/bin/bash
bold=$(tput bold)
normal=$(tput sgr0)

echo "${bold}[UPDATING)]${normal}"
echo "${bold}[Updating SOURCES (Adding docker)]${normal}"
sudo apt-get -y install apt-transport-https ca-certificates gnupg2 software-properties-common
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
sudo cp /etc/apt/sources.list /etc/apt/sources.list.bak
sudo add-apt-repository "deb [arch=armhf] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
sudo sed -i -e '/deb-src/d' -e '/^$/d' /etc/apt/sources.list
cat /etc/apt/sources.list /etc/apt/sources.list.d/*.list | less
read -p "Press any key to continue..." -n1 -s
echo ""
sudo apt-get update
echo "${bold}[Updating SYSTEM)]${normal}"
sudo apt-get dist-upgrade

echo "${bold}[INSTALLING]${normal}"
sudo apt-get -y acl aria2 armbian-config docker-ce docker-ce-cli docker-compose file glusterfs-server hdparm htop iotop lvm2 man-db mediainfo ncdu needrestart neofetch nload nmap python ranger rpcbind rsync smartmontools sshfs tmux xfsprogs

echo "${bold}[GLUSTERFS]${normal}"
echo "${bold}[Formatting filesystem]${normal}"
dd if=/dev/zero of=/dev/sda bs=512 count=1
sudo pvcreate /dev/sda
sudo vgcreate vg_glusterfs /dev/sda
sudo lvcreate --thin vg_glusterfs/oceanus_brick --extents 100%FREE --poolmetadatasize 16GB --zero n
sudo mkfs.xfs -f -i size=512 -n size=8192 /dev/vg_glusterfs/oceanus_brick
echo "${bold}[Mounting filesystem]${normal}"
sudo mkdir /mnt/oceanus
sudo cp /etc/fstab /etc/fstab.bak
cp /etc/fstab /tmp/fstab
echo "/dev/vg_glusterfs/oceanus_brick /mnt/oceanus xfs rw,inode64,noatime,nouuid 0 2" >> /tmp/fstab
sudo mv /tmp/fstab /etc/fstab
sudo mount -av
cat /etc/fstab
read -p "Press any key to continue..." -n1 -s
echo ""

sudo timedatectl set-timezone America/Los_Angeles
timedatectl set-ntp true
timedatectl
locale | grep LANG=

: sudo apt-get install 

sudo systemctl enable --now glusterd
systemctl --type=service | grep docker
systemctl --type=service | grep rpcbind
systemctl --type=service | grep glusterd

sudo rm -rf /root/.config/htop
sed -i -e '/tree_view/c\tree_view=1' ~/.config/htop/htoprc

mkdir ~/.config/neofetch
curl https://raw.githubusercontent.com/voltamage/notes/master/armbian/.config/neofetch/config.conf > ~/.config/neofetch/config.conf -#

mkdir ~/.config/aria2
curl https://raw.githubusercontent.com/voltamage/notes/master/armbian/.config/aria2/aria2.conf > ~/.config/aria2/aria2.conf -#

curl https://dn.odroid.com/5422/script/odroid.shutdown > /tmp/odroid.shutdown -#
sudo install -o root -g root -m 0755 /tmp/odroid.shutdown /lib/systemd/system-shutdown/odroid.shutdown
rm /tmp/odroid.shutdown
cat /lib/systemd/system-shutdown/odroid.shutdown

ls -la /tmp

curl https://raw.githubusercontent.com/voltamage/notes/master/armbian/scripts/maintain > ~/scripts/maintain -#
sudo chmod u+x ~/scripts/maintain
curl https://raw.githubusercontent.com/voltamage/notes/master/armbian/scripts/update > ~/scripts/update -#
sudo chmod u+x ~/scripts/update
curl https://raw.githubusercontent.com/voltamage/notes/master/armbian/scripts/fnd > ~/scripts/fnd -#
sudo chmod u+x ~/scripts/fnd
curl https://raw.githubusercontent.com/voltamage/notes/master/armbian/scripts/mfnd > ~/scripts/mfnd -#
sudo chmod u+x ~/scripts/mfnd
curl https://raw.githubusercontent.com/jbd/msrsync/master/msrsync > ~/scripts/msrsync -#
sudo chmod u+x ~/scripts/msrsync
curl https://raw.githubusercontent.com/lahwaacz/Scripts/master/rmshit.py > ~/scripts/rmshit.py -#
sudo chmod u+x ~/scripts/rmshit.py
sed -i '/.viminfo/d' ~/scripts/rmshit.py

echo "${bold}[Installing oh-my-zsh aliases]${normal}"
curl https://raw.githubusercontent.com/voltamage/notes/master/armbian/.oh-my-zsh/custom/aliases.zsh > ~/.oh-my-zsh/custom/aliases.zsh -#

echo "${bold}[DONE]${normal}"
exec zsh
